blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/timche/gmail-desktop/discussions/categories/feedback
    about: Got questions? Ask the community for help!
  - name: Feature Requests
    url: https://github.com/timche/gmail-desktop/discussions/categories/feature-requests
    about: Missing a feature? Request them here!
  - name: Feedback
    url: https://github.com/timche/gmail-desktop/discussions/categories/feedback
    about: Do you enjoy Gmail Desktop? Your feedback is much appreciated!
  - name: Development
    url: https://github.com/timche/gmail-desktop/discussions/categories/development
    about: Topics regarding current development.